### ISSUE TITLE
TennisTV [Broken]

### ISSUE THREAD

**Issue by beta2k** [pukkandan/yt-dlp#104]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.02.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\>youtube-dlc.exe --verbose --hls-prefer-native -F -p <REDACTED> -u <REDACTED> "https://www.tennistv.com/videos/montpellier-2021-r1-novak-simon"
[debug] Command-line config: ['--verbose', '--hls-prefer-native', '-F', '-p', 'PRIVATE', '-u', 'PRIVATE', 'https://www.tennistv.com/videos/montpellier-2021-r1-novak-simon']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.02.19 (exe)
[debug] Python version 3.8.7 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-essentials_build-www.gyan.dev, ffprobe 4.3.1-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[TennisTV] Logging in
[TennisTV] montpellier-2021-r1-novak-simon: Downloading webpage
ERROR: Unable to extract internal video id; please report this issue on https://github.com/pukkandan/yt-dlp . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlp  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 1010, in wrapper
  File "youtube_dlc\YoutubeDL.py", line 1031, in __extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\tennistv.py", line 72, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1011, in _search_regex
youtube_dlc.utils.RegexNotFoundError: Unable to extract internal video id; please report this issue on https://github.com/pukkandan/yt-dlp . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlp  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

Until a few days ago, this extractor still worked, but now it doesn't anymore. I think something changed with the storage of the URL id. Maybe just the regex needs to be fixed?

**Comment by pukkandan** [comment]
You left ur username/password in the description. I have removed it

**Comment by beta2k** [comment]
ugh. thank you.

**Comment by beta2k** [comment]
I think that only the regex is broken.

https://github.com/pukkandan/yt-dlp/blob/master/youtube_dlc/extractor/tennistv.py#L72

**Comment by beta2k** [comment]
thanks so much! when will there be a new release?

**Comment by pukkandan** [comment]
tomorrow if I get enough time. Otherwise, the day after
