### ISSUE TITLE
[Broken] Viki: Vikipass Plus videos cannot be downloaded

### ISSUE THREAD

**Issue by DilatoryCheetah** [pukkandan/yt-dlp#18]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.01.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dlc --netrc  --add-header "x-viki-app-ver: 2.2.5.1428709186" --add-header "x-viki-as-id: 100005a" --write-sub --sub-lang "en,ko" --sub-format srt https://www.viki.com/videos/1173419v-the-penthouse-episode-1 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--netrc', '--add-header', 'x-viki-app-ver: 2.2.5.1428709186', '--add-header', 'x-viki-as-id: 100005a', '--write-sub', '--sub-lang', 'en,ko', '--sub-format', 'srt', 'https://www.viki.com/videos/1173419v-the-penthouse-episode-1', '--verbose']
[debug] Adding header from command line option x-viki-app-ver: 2.2.5.1428709186
[debug] Adding header from command line option x-viki-as-id: 100005a
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.01.12
[debug] Python version 3.8.7 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev, ffprobe 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev
[debug] Proxy map: {}
[viki] Logging in
[viki] 1173419v: Downloading video JSON
[viki] 1173419v: Downloading new video JSON to get subtitles
WARNING: Unable to download JSON metadata: HTTP Error 500: Internal Server Error
[viki] 1173419v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://github.com/pukkandan/yt-dlc . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 888, in wrapper
  File "youtube_dlc\YoutubeDL.py", line 909, in __extract_info
  File "youtube_dlc\extractor\common.py", line 533, in extract
  File "youtube_dlc\extractor\viki.py", line 372, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1624, in _sort_formats
youtube_dlc.utils.ExtractorError: No video formats found; please report this issue on https://github.com/pukkandan/yt-dlc . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

```

## Description

I am able to download Standard shows successfully.  The error only occurs for Plus shows.

Standard urls that work:

https://www.viki.com/videos/1171276v-love-revolution-episode-1
https://www.viki.com/videos/1172605v-tale-of-the-nine-tailed-episode-1
https://www.viki.com/videos/1172625v-true-beauty-episode-1

Plus urls that give the same HTTP Error 500:

https://www.viki.com/videos/1173419v-the-penthouse-episode-1
https://www.viki.com/videos/1176903v-witches-episode-1
https://www.viki.com/videos/1176568v-a-good-supper-episode-1

**Comment by pukkandan** [comment]
Could you test it again with cookies?

**Comment by DilatoryCheetah** [comment]
I extracted cookies from viki.com using get cookies.txt.  Adding cookies results in the same error:

```
youtube-dlc --netrc  --add-header "x-viki-app-ver: 2.2.5.1428709186" --add-header "x-viki-as-id: 100005a" --write-sub --sub-lang "en,ko,zh,cht,chs" --sub-format srt --verbose --cookies viki.com_cookies.txt https://www.viki.com/videos/1173419v-the-penthouse-episode-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--netrc', '--add-header', 'x-viki-app-ver: 2.2.5.1428709186', '--add-header', 'x-viki-as-id: 100005a', '--write-sub', '--sub-lang', 'en,ko,zh,cht,chs', '--sub-format', 'srt', '--verbose', '--cookies', 'viki.com_cookies.txt', 'https://www.viki.com/videos/1173419v-the-penthouse-episode-1']
[debug] Adding header from command line option x-viki-app-ver: 2.2.5.1428709186
[debug] Adding header from command line option x-viki-as-id: 100005a
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.01.12
[debug] Python version 3.8.7 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev, ffprobe 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev
[debug] Proxy map: {}
[viki] Logging in
[viki] 1173419v: Downloading video JSON
[viki] 1173419v: Downloading new video JSON to get subtitles
WARNING: Unable to download JSON metadata: HTTP Error 500: Internal Server Error
[viki] 1173419v: Downloading MPD manifest
[viki] 1173419v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://github.com/pukkandan/yt-dlc . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 888, in wrapper
  File "youtube_dlc\YoutubeDL.py", line 909, in __extract_info
  File "youtube_dlc\extractor\common.py", line 533, in extract
  File "youtube_dlc\extractor\viki.py", line 372, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1624, in _sort_formats
youtube_dlc.utils.ExtractorError: No video formats found; please report this issue on https://github.com/pukkandan/yt-dlc . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
Do not pass the headers. yt-dlp automatically uses `'x-viki-app-ver': '4.0.57'`. As far as I know,  `2.2.5` is deprecated.

`https://www.viki.com/videos/1173419v-the-penthouse-episode-1` works for me without any additional options. I cannot test the others since I don't have an account that has access to them

**Comment by DilatoryCheetah** [comment]
If I don't pass the headers, I get a 404 error:

```
youtube-dlc --netrc --write-sub --sub-lang "en,ko,zh" --sub-format srt --verbose --cookies viki.com_cookies.txt https://www.viki.com/videos/1173419v-the-penthouse-episode-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--netrc', '--write-sub', '--sub-lang', 'en,ko,zh', '--sub-format', 'srt', '--verbose', '--cookies', 'viki.com_cookies.txt', 'https://www.viki.com/videos/1173419v-the-penthouse-episode-1']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.01.12
[debug] Python version 3.8.7 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev, ffprobe 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev
[debug] Proxy map: {}
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/pukkandan/yt-dlc . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
  File "youtube_dlc\extractor\common.py", line 633, in _request_webpage
  File "youtube_dlc\YoutubeDL.py", line 2514, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
  ```

**Comment by DilatoryCheetah** [comment]
I am running on Windows 10, if that makes a difference.

**Comment by pukkandan** [comment]
It works for me. 
But when I used a US VPN, it is giving me a 401 - which makes sense, since penthouse seems to be free in India

I did some digging on this issue and found https://github.com/ytdl-org/youtube-dl/issues/26522
The videos you are trying to download are probably DRM protected

You could try using a VPN/proxy to bypass it

**Comment by DilatoryCheetah** [comment]
Ok, using a VPN allows me to download the file.  I still had to add the headers, though.  Also, I still get a 500 error downloading the JSON metadata, but it will continue on and download the file

**Comment by pukkandan** [comment]
Since VPN is working, it is almost definitely DRM issue. Ideally, the error message should reflect this. But other than that, nothing can be done
