### ISSUE TITLE
[Broken] Pokémon TV have stopped working.

### ISSUE THREAD

**Issue by Punpki** [pukkandan/yt-dlp#24]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.01.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dlc --verbose https://watch.pokemon.com/en-us/#/player?id=3fe7752ba09141f0b0f7756d1981c6b2
[debug] System config: []
[debug] User config: []
[debug] Portable config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://watch.pokemon.com/en-us/#/player?id=3fe7752ba09141f0b0f7756d1981c6b2']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.01.16
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-7630-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] player?id=3fe7752ba09141f0b0f7756d1981c6b2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player?id=3fe7752ba09141f0b0f7756d1981c6b2: Downloading webpage
[generic] player?id=3fe7752ba09141f0b0f7756d1981c6b2: Extracting information
ERROR: Unsupported URL: https://watch.pokemon.com/en-us/#/player?id=3fe7752ba09141f0b0f7756d1981c6b2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 903, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 924, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 533, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/generic.py", line 3484, in _real_extract
    raise UnsupportedError(url)
youtube_dlc.utils.UnsupportedError: Unsupported URL: https://watch.pokemon.com/en-us/#/player?id=3fe7752ba09141f0b0f7756d1981c6b2

```

## Description

It seems that Pokémon TV have been updated once again because it is now no longer working. I noticed that the url has changed since last time I used it. Is it easy to fix by just changing the url in the yt-dlp code so it matches the new one, or is there something else you have to do?

**Comment by pukkandan** [comment]
> Is it easy to fix by just changing the url in the yt-dlp code so it matches the new one, or is there something else you have to do?

Only had to change URL since the webpage remains the same
