### ISSUE TITLE
[VLIVE] fails with "ERROR: coercing to Unicode: need string or buffer, int found" when use --download-archive

### ISSUE THREAD

**Issue by bj5p58vjahwllquoaj** [pukkandan/yt-dlp#26]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.01.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dlc -i -f "(avc1_2160P/avc1_1440P/avc1_1080P/avc1_720P/avc1_480P/avc1_360P/avc1_270P/avc1_144P)/best"
--playlist-reverse --download-archive "/home/user/youtube-dlc/archive/arc_vlive.txt" --embed-thumbnail 
--add-metadata --write-sub --convert-subs srt --all-subs --embed-subs 
-o "/home/user/youtube-dlc/Down/Vlive/[VLIVE] - E%(playlist_index)s - %(title)s.%(ext)s"  https://www.vlive.tv/channel/C1B7AF
[vlive:channel] C1B7AF: Downloading decode channel code
[vlive:channel] 984: Downloading channel list page #1
[vlive:channel] 984: Downloading channel list page #2
[vlive:channel] 984: Downloading channel list page #3
[vlive:channel] 984: Downloading channel list page #4
[vlive:channel] 984: Downloading channel list page #5
[vlive:channel] 984: Downloading channel list page #6
[vlive:channel] 984: Downloading channel list page #7
[download] Downloading playlist: IZ*ONE
[vlive:channel] playlist IZ*ONE: Collected 522 video ids (downloading 522 of them)
[download] Downloading video 1 of 522
[download] 88099 has already been recorded in archive
[download] Downloading video 2 of 522
[download] 88157 has already been recorded in archive
[download] Downloading video 3 of 522
[download] 89022 has already been recorded in archive
[download] Downloading video 4 of 522
[download] 89100 has already been recorded in archive
[download] Downloading video 5 of 522
[download] 90003 has already been recorded in archive
[download] Downloading video 6 of 522
[download] 90115 has already been recorded in archive
[download] Downloading video 7 of 522
[download] 90151 has already been recorded in archive
[download] Downloading video 8 of 522
[download] 90026 has already been recorded in archive
[download] Downloading video 9 of 522
[download] 90189 has already been recorded in archive
[download] Downloading video 10 of 522
[download] 90238 has already been recorded in archive
[download] Downloading video 11 of 522
[download] 90320 has already been recorded in archive
[download] Downloading video 12 of 522
[download] 90369 has already been recorded in archive
[download] Downloading video 13 of 522
[download] 90433 has already been recorded in archive
[download] Downloading video 14 of 522
[download] 90480 has already been recorded in archive
[download] Downloading video 15 of 522
[download] 90633 has already been recorded in archive
[download] Downloading video 16 of 522
[download] 90638 has already been recorded in archive
[download] Downloading video 17 of 522
[download] 90821 has already been recorded in archive
[download] Downloading video 18 of 522
[download] 90885 has already been recorded in archive
[download] Downloading video 19 of 522
[download] 90997 has already been recorded in archive
[download] Downloading video 20 of 522
[download] 91115 has already been recorded in archive
[download] Downloading video 21 of 522
[download] 92085 has already been recorded in archive
[download] Downloading video 22 of 522
[download] 92128 has already been recorded in archive
[download] Downloading video 23 of 522
[download] 92194 has already been recorded in archive
[download] Downloading video 24 of 522
[download] 92362 has already been recorded in archive
[download] Downloading video 25 of 522
[download] 92392 has already been recorded in archive
[download] Downloading video 26 of 522
[download] 92439 has already been recorded in archive
[download] Downloading video 27 of 522
[download] 92604 has already been recorded in archive
[download] Downloading video 28 of 522
[download] 92635 has already been recorded in archive
[download] Downloading video 29 of 522
[download] 92859 has already been recorded in archive
[download] Downloading video 30 of 522
[download] 93121 has already been recorded in archive
[download] Downloading video 31 of 522
[download] 93717 has already been recorded in archive
[download] Downloading video 32 of 522
[download] 93942 has already been recorded in archive
[download] Downloading video 33 of 522
[download] 94186 has already been recorded in archive
[download] Downloading video 34 of 522
[download] 94535 has already been recorded in archive
[download] Downloading video 35 of 522
[download] 94710 has already been recorded in archive
[download] Downloading video 36 of 522
[download] 94828 has already been recorded in archive
[download] Downloading video 37 of 522
[download] 94876 has already been recorded in archive
[download] Downloading video 38 of 522
[download] 95130 has already been recorded in archive
[download] Downloading video 39 of 522
[download] 95320 has already been recorded in archive
[download] Downloading video 40 of 522
[download] 95488 has already been recorded in archive
[download] Downloading video 41 of 522
[download] 95653 has already been recorded in archive
[download] Downloading video 42 of 522
[download] 95830 has already been recorded in archive
[download] Downloading video 43 of 522
[download] 95952 has already been recorded in archive
[download] Downloading video 44 of 522
[download] 95977 has already been recorded in archive
[download] Downloading video 45 of 522
[download] 96005 has already been recorded in archive
[download] Downloading video 46 of 522
[download] 96133 has already been recorded in archive
[download] Downloading video 47 of 522
[download] 96162 has already been recorded in archive
[download] Downloading video 48 of 522
[download] 96158 has already been recorded in archive
[download] Downloading video 49 of 522
[download] 96172 has already been recorded in archive
[download] Downloading video 50 of 522
[download] 95693 has already been recorded in archive
[download] Downloading video 51 of 522
[download] 96201 has already been recorded in archive
[download] Downloading video 52 of 522
[download] 96427 has already been recorded in archive
[download] Downloading video 53 of 522
[download] 96394 has already been recorded in archive
[download] Downloading video 54 of 522
[download] 96395 has already been recorded in archive
[download] Downloading video 55 of 522
[download] 96400 has already been recorded in archive
[download] Downloading video 56 of 522
[download] 96401 has already been recorded in archive
[download] Downloading video 57 of 522
[download] 96404 has already been recorded in archive
[download] Downloading video 58 of 522
ERROR: coercing to Unicode: need string or buffer, int found

```

## Description

Downloading vlive fails with "ERROR: coercing to Unicode: need string or buffer, int found" when it checks 58's video id from --download-archive file. It also does not ignore error, just stops. I've tried it using youtube-dl, and it works,so I've checked log on youtube-dl and found

[download] Downloading video 58 of 522
[vlive] 96407: Downloading officialVideoPost JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading video 59 of 522
[download] 96436 has already been recorded in archive

I think yt-dlp can't ignore and skips errors

**Comment by bj5p58vjahwllquoaj** [comment]
I've checked log on youtube-dl and found

[download] Downloading video 58 of 522
[vlive] 96407: Downloading officialVideoPost JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading video 59 of 522

I think yt-dlp can't ignore and skips errors

**Comment by pukkandan** [comment]
The problem happened coz the video ID is a number. I'll fix it asap

**Comment by pukkandan** [comment]
I have fixed it. Next time, please post the verbose output. It is very helpful in identifying the issue.

'''
ERROR: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:\AKJ\Progs\yt-dlc\youtube_dlc\YoutubeDL.py", line 904, in wrapper
    return func(self, *args, **kwargs)
  File "D:\AKJ\Progs\yt-dlc\youtube_dlc\YoutubeDL.py", line 941, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:\AKJ\Progs\yt-dlc\youtube_dlc\YoutubeDL.py", line 1031, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "D:\AKJ\Progs\yt-dlc\youtube_dlc\YoutubeDL.py", line 1159, in __process_playlist
    if self._match_entry(entry, incomplete=True) is not None:
  File "D:\AKJ\Progs\yt-dlc\youtube_dlc\YoutubeDL.py", line 846, in _match_entry
    reason = check_filter()
  File "D:\AKJ\Progs\yt-dlc\youtube_dlc\YoutubeDL.py", line 835, in check_filter
    if self.in_download_archive(info_dict):
  File "D:\AKJ\Progs\yt-dlc\youtube_dlc\YoutubeDL.py", line 2376, in in_download_archive
    vid_id = self._make_archive_id(info_dict)
  File "D:\AKJ\Progs\yt-dlc\youtube_dlc\YoutubeDL.py", line 2368, in _make_archive_id
    extractor.lower() + video_id
TypeError: can only concatenate str (not "int") to str
'''

btw, on an unrelated note, you can use `-S proto` instead of the long format string you are using
