### ISSUE TITLE
youtube error reported as warning

### ISSUE THREAD

**Issue by werid** [pukkandan/yt-dlp#33]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/channel/UCtPNhpgB_mjKxa4495_PfvQ/videos']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.01.24
[debug] Python version 3.7.9 (CPython) - FreeBSD-12.2-RELEASE-p1-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] UCtPNhpgB_mjKxa4495_PfvQ: Downloading webpage
WARNING: YouTube said: ERROR - This account has been terminated because we received multiple third-party claims of copyright infringement regarding material the user posted.
ERROR: Unable to recognize tab page; please report this issue on https://github.com/pukkandan/yt-dlp . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlp  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/weird/.local/lib/python3.7/site-packages/youtube_dlc/YoutubeDL.py", line 945, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weird/.local/lib/python3.7/site-packages/youtube_dlc/YoutubeDL.py", line 966, in __extract_info
    ie_result = ie.extract(url)
  File "/home/weird/.local/lib/python3.7/site-packages/youtube_dlc/extractor/common.py", line 533, in extract
    ie_result = self._real_extract(url)
  File "/home/weird/.local/lib/python3.7/site-packages/youtube_dlc/extractor/youtube.py", line 3392, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dlc.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://github.com/pukkandan/yt-dlp . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlp  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

A youtube error (e.g. terminated account) is reported as a warning instead of an error, and then yt-dlp throws an error of its own.

**Comment by pukkandan** [comment]
This was done in order to report all errors/warnings correctly (yes, sometimes a page has multiple errors) instead of simply throwing the first error. I have now made a patch that will throw the last error message and  print warnings from the other ones
