### ISSUE TITLE
[Question] Why can module mutagen not be found (Windows 7)

### ISSUE THREAD

**Issue by nicolaasjan** [pukkandan/yt-dlp#39]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I installed the mutagen module with: `python -m pip install mutagen` and according to `pip list` that was successful:

```
C:\Users\Nico>pip list
Package                   Version
------------------------- ---------
altgraph                  0.17
cffi                      1.14.2
future                    0.18.2
mutagen                   1.45.1
pefile                    2019.4.18
pip                       21.0
pycparser                 2.20
pyinstaller               4.0
pyinstaller-hooks-contrib 2020.7
pywin32                   228
pywin32-ctypes            0.2.0
setuptools                49.2.1
```
But when downloading an `opus` file I get:

```
PS C:\Windows\system32> youtube-dlc -v -x -f bestaudio https://www.youtube.com/watch?v=UsYkLXycbYU
[debug] User config file: C:\Users\Nico\AppData\Roaming\youtube-dlc\config.txt
[debug] User config: ['--no-mtime', '-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaud
io[ext=m4a]/best[ext=mp4]/best', '--embed-thumbnail']
[debug] Command-line config: ['-v', '-x', '-f', 'bestaudio', 'https://www.youtube.com/watch?v=UsYkLXycbYU']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.01.28.2
[debug] Python version 3.8.6 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2021-01-05-git-66deab3a26-full_build-www.gyan.dev, ffprobe 2021-01-05-git-66deab3a26-full_b
uild-www.gyan.dev
[debug] Proxy map: {}
[youtube] UsYkLXycbYU: Downloading webpage
[youtube] {18} signature length 108, html5 player c6df6ed7
[youtube] {134} signature length 108, html5 player c6df6ed7
[youtube] {243} signature length 108, html5 player c6df6ed7
[youtube] {133} signature length 108, html5 player c6df6ed7
[youtube] {242} signature length 108, html5 player c6df6ed7
[youtube] {160} signature length 108, html5 player c6df6ed7
[youtube] {278} signature length 108, html5 player c6df6ed7
[youtube] {140} signature length 108, html5 player c6df6ed7
[youtube] {249} signature length 104, html5 player c6df6ed7
[youtube] {250} signature length 108, html5 player c6df6ed7
[youtube] {251} signature length 108, html5 player c6df6ed7
[debug] Sort order given by user:
[debug] Formats sorted by: lang, quality, hasvid, ie_pref, res, fps, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr,
 asr, proto, vext, aext, hasaud, source, id
[info] Downloading format(s) 251
[youtube] UsYkLXycbYU: Downloading thumbnail ...
[youtube] UsYkLXycbYU: Writing thumbnail to: C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.jpg
[debug] Invoking downloader on 'https://r5---sn-5hne6n7z.googlevideo.com/videoplayback?expire=1611869276&ei=_NcSYML8C9XT
gQeflpL4DA&ip=<REDACTED>&id=o-AKy-1f0Oh5WyPqfvvYSqg5p7jKcjB9ci3L_tYiigmU5e&itag=251&source=youtube&requiressl=yes&mh
=tm&mm=31%2C29&mn=sn-5hne6n7z%2Csn-5hnedn7e&ms=au%2Crdu&mv=m&mvi=5&pl=15&pcm2=yes&initcwndbps=1657500&vprv=1&mime=audio%
2Fwebm&ns=2aU6zNO_352kqqonX1cwiyMF&gir=yes&clen=2481451&dur=200.841&lmt=1496705555203583&mt=1611847249&fvip=5&keepalive=
yes&c=WEB&n=V4ujU06mIc0noEsteJsM&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2C
gir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgOe44R4bymutvwbFKWAawCQt
JiYKDMeE8fvIacHuZHCICIHdoR8FWh83MZMoenO7P3PBNQ89ICK1JQLk2wgolHADF&sig=AOq0QJ8wRgIhANk5mgaNvb-1cXv0SzzrhImdOC7m6vStg-Xf89
_EMCiHAiEApfNk4nPcWD8VNScJvaZ1wpSkzrLpEyFXh71EgfGeRdc=&ratebypass=yes'
[download] Destination: C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.webm
[download] 100% of 2.37MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.
webm"
[ExtractAudio] Destination: C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.opus
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Nico\Desktop\cuby and the blizzards win
dow of my eyes.webm" -vn -acodec copy "file:C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.opus"
Deleting original file C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.webm (pass -k to keep)
[EmbedThumbnail] Correcting extension to webp and escaping path for thumbnail "C:\Users\Nico\Desktop\cuby and the blizza
rds window of my eyes.jpg"
[EmbedThumbnail] Converting thumbnail "C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.webp" to JPEG
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Nico\Desktop\cuby and the blizzards win
dow of my eyes.webp" "-bsf:v" mjpeg2jpeg "file:C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.jpg"
ERROR: module mutagen was not found. Please install.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 2459, in run_pp
  File "youtube_dlc\postprocessor\embedthumbnail.py", line 156, in run
youtube_dlc.postprocessor.embedthumbnail.EmbedThumbnailPPError: module mutagen was not found. Please install.
```
Path variables:
`C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\mpv\;C:\Users\Nico\AppData\Roaming\Python\Python38\Scripts\;C:\Users\Nico\AppData\Roaming\Python\Python38\`

**Comment by pukkandan** [comment]
Try using `py -m pip install mutagen`. By default, `python` points to python2 and `py` to python3

**Comment by pukkandan** [comment]
btw, how are you running it? I can't see your git HEAD in the debug.

Did you compile it yourself? If so, it may not work. When you compile, the necessary packages must also be compiled alongside. So some changes will have to be made in `make_win`. I suggest you either wait till I make the next release, or run from source

**Comment by nicolaasjan** [comment]
> btw, how are you running it? I can't see your git HEAD in the debug.
> 
> Did you compile it yourself? If so, it may not work. When you compile, the necessary packages must also be compiled alongside. So some changes will have to be made in `make_win`. I suggest you either wait till I make the next release, or run from source

Yes, I compiled myself with `pyinst.py`, not knowing that the necessary packages needed to be compiled alongside.
I was thinking that it should work on Windows, because it also worked on Linux. My bad...

**Comment by pukkandan** [comment]
> Sorry for the inconvenience.

No inconvenience for me. Dont worry about it :)

**Comment by nicolaasjan** [comment]
(offtopic)
Now that you're here; how would a Windows batch file look like.

`cd`to `C:\Users\Nico\Desktop\yt-dlp-master\youtube_dlc` and then call `__main__.py`.
I can then use that in my "Open With" context menu in the browser.

**Comment by pukkandan** [comment]
```
@cd /d "C:\Users\Nico\Desktop\yt-dlp-master\youtube_dlc"
@py __main__.py
```

But cd into the folder will cause all relative paths to be set from there. So you probably don't want to do that. If you want to retain your cd,  you can just use the `youtube-dlc.cmd` in the repo. Or, you could do:

```
@cd /d "PATH YOU WANT TO BE CD"
@py "C:\Users\Nico\Desktop\yt-dlp-master\youtube_dlc\__main__.py"
```

**Comment by pukkandan** [comment]
Can you check the release and confirm that mutagen imports correctly? I dont have a win7 system to check

**Comment by nicolaasjan** [comment]
> Can you download the release and confirm that mutagen imports correctly? I dont have a win7 system to check

Yes, I can confirm it works!
(thumbnail visible in the media player)

```
PS C:\Windows\system32> youtube-dlc -v -x -f bestaudio https://www.youtube.com/watch?v=UsYkLXycbYU
[debug] User config file: C:\Users\Nico\AppData\Roaming\youtube-dlc\config.txt
[debug] User config: ['--no-mtime', '-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaud
io[ext=m4a]/best[ext=mp4]/best', '--embed-thumbnail']
[debug] Command-line config: ['-v', '-x', '-f', 'bestaudio', 'https://www.youtube.com/watch?v=UsYkLXycbYU']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.01.29
[debug] Python version 3.8.7 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2021-01-27-git-149bfc2445-full_build-www.gyan.dev, ffprobe 2021-01-27-git-149bfc2445-full_b
uild-www.gyan.dev
[debug] Proxy map: {}
[youtube] UsYkLXycbYU: Downloading webpage
[youtube] {18} signature length 103, html5 player 7bc032d0
[youtube] UsYkLXycbYU: Downloading player https://www.youtube.com/s/player/7bc032d0/player_ias.vflset/en_US/base.js
[youtube] {134} signature length 107, html5 player 7bc032d0
[youtube] UsYkLXycbYU: Downloading player https://www.youtube.com/s/player/7bc032d0/player_ias.vflset/en_US/base.js
[youtube] {243} signature length 107, html5 player 7bc032d0
[youtube] {133} signature length 107, html5 player 7bc032d0
[youtube] {242} signature length 103, html5 player 7bc032d0
[youtube] {160} signature length 107, html5 player 7bc032d0
[youtube] {278} signature length 103, html5 player 7bc032d0
[youtube] {140} signature length 107, html5 player 7bc032d0
[youtube] {249} signature length 107, html5 player 7bc032d0
[youtube] {250} signature length 107, html5 player 7bc032d0
[youtube] {251} signature length 107, html5 player 7bc032d0
[debug] Sort order given by user:
[debug] Formats sorted by: lang, quality, hasvid, ie_pref, res, fps, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr,
 asr, proto, vext, aext, hasaud, source, id
[info] Downloading format(s) 251
[youtube] UsYkLXycbYU: Downloading thumbnail ...
[youtube] UsYkLXycbYU: Writing thumbnail to: C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.jpg
[debug] Invoking downloader on 'https://r5---sn-5hne6n7z.googlevideo.com/videoplayback?expire=1611969472&ei=YF8UYKCZIZ6O
1gKk5buACA&ip=<REDACTED>&id=o-AI6lvENE687GGekrN4VsEVcFESchwSymw2pHnzwBTlws&itag=251&source=youtube&requiressl=yes&mh
=tm&mm=31%2C29&mn=sn-5hne6n7z%2Csn-5hnedn7e&ms=au%2Crdu&mv=m&mvi=5&pl=15&initcwndbps=1371250&vprv=1&mime=audio%2Fwebm&ns
=M8vcUVUxSbTwqdbndOANbwUF&gir=yes&clen=2481451&dur=200.841&lmt=1496705555203583&mt=1611947589&fvip=5&keepalive=yes&c=WEB
&n=TdaSzs_oDsacZynBc&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2C
lmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgaCt9fO7IKEbqO4cwJjWXVjeZ53-v99S50bLFI8srS2
ECIQCWdiDwNEmJc2jIUGGzDh0-TwB6K6RhVO5HVcZYRMG4Kw%3D%3D&sig=AOq0QJ8wRQIhAP5k-9BXxnKHYbeuR3uZ_beXnNy9ikLPWWF2PfDQBlzFAiBrC
l0KgANnJ1wUGyaKSBsKkXAFjlYNs7BMDwR09Dek1g==&ratebypass=yes'
[download] Destination: C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.webm
[download] 100% of 2.37MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.
webm"
[ExtractAudio] Destination: C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.opus
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Nico\Desktop\cuby and the blizzards win
dow of my eyes.webm" -vn -acodec copy "file:C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.opus"
Deleting original file C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.webm (pass -k to keep)
[EmbedThumbnail] Correcting extension to webp and escaping path for thumbnail "C:\Users\Nico\Desktop\cuby and the blizza
rds window of my eyes.jpg"
[EmbedThumbnail] Converting thumbnail "C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.webp" to JPEG
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Nico\Desktop\cuby and the blizzards win
dow of my eyes.webp" "-bsf:v" mjpeg2jpeg "file:C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.jpg"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Nico\Desktop\cuby and the blizzards win
dow of my eyes.jpg" -hide_banner "file:C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.jpg"
Deleting original file C:\Users\Nico\Desktop\cuby and the blizzards window of my eyes.jpg (pass -k to keep)


```

**Comment by nicolaasjan** [comment]
PS
I don't see `make_win.bat`, `pyinst.py` and `pyinst32.py` any more?

**Comment by pukkandan** [comment]
> I don't see make_win.bat, pyinst.py and pyinst32.py any more?

I combined pyinst with pyinst32 and moved it inside devscripts. You can run `py devscripts\pyinst.py 64` or `py devscripts\pyinst.py 32` to build. I've updated the instructions in https://github.com/pukkandan/yt-dlp#compile

make_win code was outdated, so I removed it.

relevent commit: https://github.com/pukkandan/yt-dlp/commit/e38df8f9fa4d715513453928591346f680dbe298

---

I am closing this issue

**Comment by nicolaasjan** [comment]
Sorry for my ignorance; but can the 32-bit version also be built with 64-bit Python?

**Comment by pukkandan** [comment]
I dont think so. youtube-dlc's documentation alteast said it can't
