### ISSUE TITLE
[Broken] Youtube age-restricted video gives ERROR: expected string or bytes-like object

### ISSUE THREAD

**Issue by werid** [pukkandan/yt-dlp#51]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.01.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['--cookies', '../etc/cookies.txt', '--verbose', 'EX_8ZjT2sO4']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.01.29
[debug] Python version 3.7.9 (CPython) - FreeBSD-12.2-RELEASE-p1-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] EX_8ZjT2sO4: Downloading webpage
[youtube] EX_8ZjT2sO4: Downloading embed webpage
ERROR: expected string or bytes-like object
Traceback (most recent call last):
  File "/home/weird/.local/lib/python3.7/site-packages/youtube_dlc/YoutubeDL.py", line 980, in wrapper
    return func(self, *args, **kwargs)
  File "/home/weird/.local/lib/python3.7/site-packages/youtube_dlc/YoutubeDL.py", line 1001, in __extract_info
    ie_result = ie.extract(url)
  File "/home/weird/.local/lib/python3.7/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/weird/.local/lib/python3.7/site-packages/youtube_dlc/extractor/youtube.py", line 1727, in _real_extract
    playable_in_embed = re.search(r'{\\\"playableInEmbed\\\":(?P<playableinEmbed>[^\,]+)', ext)
  File "/usr/local/lib/python3.7/re.py", line 185, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

## Description

age-restricted videos on youtube fail with an ERROR: expected string or bytes-like object. works in latest youtube-dl.

**Comment by pukkandan** [comment]
The youtube extractor has to be entirely rewritten - again. Luckily, youtube-dl devs has already done most of the work. I am working on merging it

**Comment by pukkandan** [comment]
Fixed now.

```
$ youtube-dlc EX_8ZjT2sO4
[youtube] EX_8ZjT2sO4: Downloading webpage
[youtube] EX_8ZjT2sO4: Refetching age-gated info webpage
[info] Downloading format(s) 248+251
[download] Destination: Grenouer - Alone in the Dark - [UNCENSORED - AGE RESTRICTED] [EX_8ZjT2sO4].f248.webm
[download]  20.6% of 19.01MiB at  2.74MiB/s ETA 00:05
ERROR: Interrupted by user
```

Close the issue once you have confirmed
