### ISSUE TITLE
[YouTube] "--get-comments" does not work.

### ISSUE THREAD

**Issue by Punpki** [pukkandan/yt-dlp#53]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.02.04**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
youtube-dlc --verbose --get-comments https://www.youtube.com/watch?v=5nW9o6M5zFo
[debug] Command-line config: ['--verbose', '--get-comments', 'https://www.youtube.com/watch?v=5nW9o6M5zFo']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.01.29
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-7642-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] 5nW9o6M5zFo: Downloading webpage
[debug] Sort order given by user: 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1004, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1025, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 2003, in _real_extract
    continuation, itct = continuations.pop()
ValueError: too many values to unpack (expected 2)

```

## Description

I've tried the command "--get-comments" with several videos on YouTube but it only shows that error every time.

**Comment by pukkandan** [comment]
Fixed now. You can try out the current master

**Comment by Punpki** [comment]
It works perfectly. All these new features are amazing. Thank you so much for all the work!

**Comment by pukkandan** [comment]
No problem. You can thank @bbepis for the comment download code
