### ISSUE TITLE
[Broken] (YouTube) ERROR: 'list' object has no attribute 'run'

### ISSUE THREAD

**Issue by nicolaasjan** [pukkandan/yt-dlp#62]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.02.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dlc -v --ignore-config -f bestvideo"[height<=1080][ext=mp4]"+bestaudio[ext=m4a]/best[ext=mp4]/best https://www.youtube.com/watch?v=_KrBFF5SsIM
[debug] Command-line config: ['-v', '--ignore-config', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'https://www.youtube.com/watch?v=_KrBFF5SsIM']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.02.08
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-65-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-100984-g6b8ef51-Nico-20210206, ffprobe N-100984-g6b8ef51-Nico-20210206
[debug] Proxy map: {}
[youtube] _KrBFF5SsIM: Downloading webpage
[debug] Sort order given by user: 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Downloading format(s) 137+140
[debug] Invoking downloader on 'https://r4---sn-5hnekn76.googlevideo.com/videoplayback?expire=1612829427&ei=k34hYJeFEMGAx_AP06mt6Ak&ip=<REDACTED>&id=o-AGYJihmcH0U7Uypp314OfKlmRS7KnNxpAXf1Bjct7Jam&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=VL&mm=31%2C29&mn=sn-5hnekn76%2Csn-5hne6ns6&ms=au%2Crdu&mv=m&mvi=4&pl=15&initcwndbps=1968750&vprv=1&mime=video%2Fmp4&ns=yIp8MKKsSsIgv5uC5N_JTr4F&gir=yes&clen=44790035&dur=216.666&lmt=1612638320638890&mt=1612807245&fvip=4&keepalive=yes&c=WEB&txp=5432434&n=h50pqQtqUDhYJFV&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALl5M-YjQw79LNQYi3QiscgzJ-9715jCXWc8VeaIhbYHAiEA-qWs_thKPDNZzVvSCaOx7fLGk0ST_2420y7Xn441VR4%3D&sig=AOq0QJ8wRgIhAOK4a6nHgd7N6k83O9StSHddSAtx5V9HcbKA2r-NZ1AkAiEAuWOqM2UFmgVqYL3sj7DRTz46iMeegmARvZQpByLBqjI='
[download] Destination: Golden Earring - Another 45 miles (2015, HD quality) [_KrBFF5SsIM].f137.mp4
[download] 100% of 42.72MiB in 00:07
[debug] Invoking downloader on 'https://r4---sn-5hnekn76.googlevideo.com/videoplayback?expire=1612829427&ei=k34hYJeFEMGAx_AP06mt6Ak&ip=<REDACTED>&id=o-AGYJihmcH0U7Uypp314OfKlmRS7KnNxpAXf1Bjct7Jam&itag=140&source=youtube&requiressl=yes&mh=VL&mm=31%2C29&mn=sn-5hnekn76%2Csn-5hne6ns6&ms=au%2Crdu&mv=m&mvi=4&pl=15&initcwndbps=1968750&vprv=1&mime=audio%2Fmp4&ns=yIp8MKKsSsIgv5uC5N_JTr4F&gir=yes&clen=3508312&dur=216.735&lmt=1612593055319960&mt=1612807245&fvip=4&keepalive=yes&c=WEB&txp=5432434&n=h50pqQtqUDhYJFV&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJwTXbNt0Leod0jIGdlDUCzJ6GCsOadv1dGKUGUqqQyjAiEAut24Fn7FtmfYxs6Av70YCckDEsf2ghF0Tn7l7SLwEKk%3D&sig=AOq0QJ8wRgIhAN8b7zkCUmGnptZsIr7tJtWP-199WFq97G_LcYrh3bReAiEA6dxuQNHz66chnhULTuOeWKtAbudf6YM1JZm3djkrFNQ='
[download] Destination: Golden Earring - Another 45 miles (2015, HD quality) [_KrBFF5SsIM].f140.m4a
[download] 100% of 3.35MiB in 00:00
ERROR: 'list' object has no attribute 'run'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1004, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1041, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1073, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1943, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 2437, in process_info
    self.post_process(dl_filename, info_dict, files_to_move)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 2543, in post_process
    files_to_move, info = self.run_pp(pp, info, files_to_move)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 2512, in run_pp
    files_to_delete, infodict = pp.run(infodict)
AttributeError: 'list' object has no attribute 'run'

```

## Description

With the latest `master` version I have:
`ERROR: 'list' object has no attribute 'run'`  The partial files download fine, but don't combine.

**Comment by nicolaasjan** [comment]
Now it works again.
Thank you very much for your fast fix!

**Comment by pukkandan** [comment]
it was a dumb mistake I made :D
