### ISSUE TITLE
Cant download age restricted videos

### ISSUE THREAD

**Issue by FlyingThunder** [pukkandan/yt-dlp#81]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running yt-dlp version **2021.02.09**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
C:\Users\laure\PycharmProjects\DiscordBot>youtube-dlc https://www.youtube.com/watch?v=7t0SqerlBA0 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=7t0SqerlBA0', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-07-21-b5f1e05
[debug] Proxy map: {}
[youtube] 7t0SqerlBA0: Downloading webpage
[youtube] 7t0SqerlBA0: Downloading embed webpage
Traceback (most recent call last):
  File "youtube_dlc\__main__.py", line 19, in <module>
  File "youtube_dlc\__init__.py", line 487, in main
  File "youtube_dlc\__init__.py", line 477, in _real_main
  File "youtube_dlc\YoutubeDL.py", line 2103, in download
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 1873, in _real_extract
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\re.py", line 201, in search
TypeError: expected string or bytes-like object
[9788] Failed to execute script __main__

```

## Description

both the original youtube-dlc and this fork fail to download age restricted videos, which was previously possible with youtube-dlc *without* the use of cookies or advanced methods

**Comment by pukkandan** [comment]
> [debug] youtube-dlc version 2020.11.11-3

Update to latest version

```
$ youtube-dlc https://www.youtube.com/watch?v=7t0SqerlBA0 -v
[debug] Command-line config: ['https://www.youtube.com/watch?v=7t0SqerlBA0', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.02.09
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 068693675
[debug] Python version 3.8.4 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] 7t0SqerlBA0: Downloading webpage
[youtube] 7t0SqerlBA0: Refetching age-gated info webpage
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) 315+251
[debug] Invoking downloader on 'https://r4---sn-gwpa-jv36.googlevideo.com/videoplayback?expire=1613276323&ei=Q1AoYNusEKuH3LUP_dOmiAc&ip=2405%3A201%3Af003%3Abdb6%3A50ab%3A5e1c%3Adb66%3Ad225&id=o-AIp5jC8iTHvHLBjTjWDfPWf8lbFOLTnJxAoyCxFqNCTd&itag=315&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315&source=youtube&requiressl=yes&mh=oD&mm=31%2C29&mn=sn-gwpa-jv36%2Csn-gwpa-h55s&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=38&initcwndbps=338750&vprv=1&mime=video%2Fwebm&ns=_SSN2XgOQdqiTOrsCOTpigcF&gir=yes&clen=198068014&dur=59.999&lmt=1580884488002358&mt=1613254362&fvip=6&keepalive=yes&c=WEB&txp=1301222&n=AHnIzYWncY5JGTNWMz&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgK3Bf7XJiUjQjt9pYXonbjkw2wXnMAcmC27Qoh6KDH2QCIE6Ox3nQT3kTGE6IEyvLazmdS5CIiiZEIwlzRVxbT0Kv&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAP5AG2M8AuDEjjOWC7LXMzFw5QrPNeKerwOJXN-1jgJbAiAfuq7QVnhM746B5Tnmap7vlXwhvRNdlQ3SylaRUFhy0g%3D%3D'
[download] Destination: Test Age Restricted Video [7t0SqerlBA0].f315.webm
[download]   1.1% of 188.89MiB at  2.35MiB/s ETA 01:19
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
@FlyingThunder I'm closing this since you haven't responded
