### ISSUE TITLE
An extractor error has occurred. (caused by KeyError('runs'))

### ISSUE THREAD

**Issue by Rings4** [pukkandan/yt-dlp#97]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.02.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
[download] Downloading video 8 of 9
[youtube] EnBCBttyRX8: Downloading webpage
[debug] Sort order given by user: 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[youtube] Downloading comments
[youtube] Comments downloaded: 1 of ~120 (chain UgjLwnAHOojJ6HgCoAEC)
[youtube] Comments downloaded: 4 of ~120 (chain UgwXhPNEz3VYetdqL5d4AaABAg)
[youtube] Comments downloaded: 10 of ~120 (chain UggLPt8Ss9yPBngCoAEC)
[youtube] Comments downloaded: 16 of ~120 (chain Ugi20oe8lysu2ngCoAEC)
[youtube] Comments downloaded: 19 of ~120 (chain Ugi780WzuK01QHgCoAEC)
[youtube] Comments downloaded: 26 of ~120 (chain UgxAJs-jzAeWuZ_Iwul4AaABAg)
[youtube] Comments downloaded: 31 of ~120 (chain UgwPGFU5QdK0_DgGD-14AaABAg)
[youtube] Comments downloaded: 33 of ~120 (chain UgjgIpsr_UnUpXgCoAEC)
[youtube] Comments downloaded: 40 of ~120 (chain UgjzcAbGhNoY23gCoAEC)
[youtube] Comments downloaded: 47 of ~120 (chain UggMhYGSmml9S3gCoAEC)
[youtube] Comments downloaded: 49 of ~120
[youtube] Comments downloaded: 51 of ~120 (chain Ugi5-XWBDKcDvHgCoAEC)
[youtube] Comments downloaded: 60 of ~120 (chain Ugjgm78bCVmn23gCoAEC)
[youtube] Comments downloaded: 66 of ~120 (chain UgxZSZ8-4dliWwXyo-B4AaABAg)
[youtube] Comments downloaded: 71 of ~120 (chain UggkMOiAp9iGiHgCoAEC)
[youtube] Comments downloaded: 77 of ~120
ERROR: An extractor error has occurred. (caused by KeyError('runs')); please report this issue on https://github.com/pukkandan/yt-dlp . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlp  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 2067, in _real_extract
KeyError: 'runs'
Traceback (most recent call last):
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 2067, in _real_extract
KeyError: 'runs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 1006, in wrapper
  File "youtube_dlc\YoutubeDL.py", line 1027, in __extract_info
  File "youtube_dlc\extractor\common.py", line 545, in extract
youtube_dlc.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('runs')); please report this issue on https://github.com/pukkandan/yt-dlp . Make sure you are using the latest version; see  https://github.com/pukkandan/yt-dlp  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE
Trying to archive the following channel (https://www.youtube.com/user/spike354). All 9 videos downloaded properly with youtube-dl, but this fork gives an error for 2 videos and can only manage to download 7 of them. One of the videos that don't work is this: https://www.youtube.com/watch?v=EnBCBttyRX8

**Comment by pukkandan** [comment]
I have fixed this specific issue. But due to the way `--get-comments` is implemented, there are a lot of potential bugs just waiting to be found. 

The whole comment extraction should probably be re-written
